spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supportStudent
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

signer_key: ${SIGNER_KEY}

cloudinary_cloud_name: ${CLOUDINARY_CLOUD_NAME}
cloudinary_api_key: ${CLOUDINARY_API_KEY}
cloudinary_api_secret: ${CLOUDINARY_API_SECRET}